init:
  - git config --global core.autocrlf input

build_script:
  - build.cmd /v:normal

deploy:
  - provider: NuGet
    api_key:
      secure: 7MS5+XWaFchMXFqzgneQCqo9U0DlxiPXe/KWWUnbCBDEizVn06EjdQZkWu1gbNOJ
    artifact: /.*\.nupkg/
    on:
      branch: master

  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
		secure: R9sB6B+4wcCcwie1muUXWBA+ZCZmh9YWkIcDkuh3OoaSYVwyPLTrBzfl38IS0I2c
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
      
nuget:
  project_feed: true
  disable_publish_on_pr: true
  
artifacts:
  - path: '*.nupkg'
    name: Packages